### ISSUE TITLE
Struttura directory

### ISSUE THREAD

**Issue by giodabg** [EMoscatello/Progetto_Lettura_contatore#18]
Tutti i branch devono condividere la seguente struttura di directory:

- **Documentazione** (contenente tutta la documentazione ufficiale che verrà valutata dai prof e dall'azienda)
- **Prototipo.0.9** (contenente tutto il codice sorgente, i file SQL, il file Install.txt)
- **Archivio** (tutte le directory, i documenti, gli zip, ...  che non si utilizzano più)

Proposta di operazioni per la riorganizzazione:

- [x] Rinominare **Documenti** in **Documentazione**
- [ ] Rinominare **Bozze** in **Archivio**
- [x] Spostare **GUI** in **Documentazione**
- [x] Rinominare **Lavori in corso** in **Prototipo.0.9** 
- [x] Spostare **Codice/firmware** in **Archivio**

Il codice di prova/test deve trovarsi sempre nella directory "Prototipo.0.9" all'interno del proprio branch.

Alla fine della settimana si procede con la sincronizzazione nel main in modo da ripartire il lunedì da una situazione identica per tutto il gruppo.

**Comment by EMoscatello** [comment]
Aggiornamento eseguito!!!

Ho anche caricato in prototipo il video di dimostrazione del funzionamento del digitalizzatore
